### PR TITLE
Fix AppStore submission by removing EMBEDDED_CONTENT_CONTAINS_SWIFT=YES.

### LINKED ISSUE #42: Cannot submit to the app store
The ReactKit framework (built with Carthage) includes a Frameworks folder containing the Swift standard library, which prevents apps from being submitted to the app store:

screen shot 2015-06-12 at 12 47 48 pm

Deleting the Frameworks folder resolves the issue, but it would be nice to not have this step.

I'll submit a pull request if I can figure out the reason, but after a bit of digging I came up empty.

### PR DESCRIPTION
**Pull request by inamiy**
This pull request will fix #42 wrong embedding of Swift frameworks to ReactKit.framework,
and also fixes iOS test by copying framework as discussed below: 

[Could you provide more details in readme on how to consume your framework · Issue #114 · typelift/Swiftz](https://github.com/typelift/Swiftz/issues/114#issuecomment-61909307)

@wtmoose Can you please check this? :pray:

### CODE REVIEW

**Comment by wtmoose** [comment]
This doesn't seem to fix the issue. I'd already tried this [on my fork](https://github.com/wtmoose/ReactKit/commit/1414d71aa239bfd0dcb0502921989c003ae47576) before filing #42.

**Comment by inamiy** [comment]
Have you tried cleaning (`shift + K`, or `cmd + alt + shift + K`)?
It seems `ReactKit.framework/Frameworks` directory keeps alive unless you do cleaning.

**Comment by wtmoose** [comment]
I've deleted my entire derived data folder, the Carthage sources and the Carthage build.

Do you not see this issue in your own builds?

**Comment by inamiy** [comment]
I could successfully uploaded demo app ReactKit/ReactKitCatalog@190209f (appstore-submission branch) using current fix 37ad0a1.
In this app, dependency frameworks are drag-n-dropped to app xcodeproj and built via Xcode IDE, 
but I also tested using `Carthage/Build/iOS` folder and it worked fine too.

Please check if your `Carthage/Checkouts/ReactKit` is pointing to current fix 37ad0a1, not v0.11.0.

**Comment by wtmoose** [comment]
Yes, I'm pointing at https://github.com/ReactKit/ReactKit/commit/37ad0a1e809039442cca18894821179d14c498bc, but I still get the Frameworks directory. It sounds as if its probably a problem on my end. I'll try to look into it further soon.

**Comment by inamiy** [comment]
Hm... that's strange :confused:

At least, this pull request will solve AppStore submission of demo app [ReactKitCatalog](https://github.com/ReactKit/ReactKitCatalog),
so I will merge this for now and bump as v0.11.1.

Please try v0.11.1 once more, and if you still have trouble, let's keep discussion in #42.

**Pull request merged**
