### PR TITLE
Refactor code for Swift 1.2.

### PR DESCRIPTION
**Pull request by inamiy**
This pull request is a **BREAKING CHANGE** where not only fixing for Swift 1.2 but also refactoring whole codes as follows:

- [x] 1. Rename `Signal<T>` to `Stream<T>`
- [x] 2. Stream-operation functions
  - [x] 1. Move functions outside of `Stream<T>` class for better type-constraints.
  - [x] 2. Rename e.g. `merge`, `mergeAll`, `mergeInner` & always use `**All` (stream-array) and `**Inner` (nested-stream) naming conventions
  - [x] 3. Add more useful operations
    - [x] `distinct()`
    - [x] `distinctUntilChanged()`
    - [x] `reduce()`
    - [x] `interval()`
    - [x] `switchLatestInner()`
    - [x] `prestart()` (a.k.a `Rx.replay`)
    - [x] `catch()`
    - [x] `retry()`
    - [x] `repeat()`
- [x] 3. Add stream pipe operator `|>` and stream-producer pipe operator `|>>` in replace of dot-method-chaining syntax.
- [x] 4. Add terminal reacting operator `~>! ()` to collect synchronously-emitted values (useful just like Java 8 Stream API)
- [x] 5. Update README.md

### CODE REVIEW

**Comment by DarthMike** [comment]
@inamiy First of all, thanks for the lib! 

I've got an observation, why do you want to rename Signal<T> to Stream<T> ?  Signal already implies stream of values, doesn't it?

**Comment by inamiy** [comment]
@DarthMike Hi, thanks for question :smile: 

Though `Signal` is fairly common term in some languages including ReactiveCocoa in ObjC/Swift, I find `Stream` is more suitable due to the following reasons:

- `ReactKit.Stream` is now getting very similar to Java 8 Stream API, [matz/streem](https://github.com/matz/streem), and even existing NSInputStream.
- Naming upper & lower streams as `upstream` & `downstream` improves (core) code readability ("upsignal" & "downsignal" were not torelable to me :triumph:)
- `Signal` (may) confuses with POSIX signal.

And above all, I like the phrase "Everything is a stream" in [The introduction to Reactive Programming you've been missing](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754).

**Comment by DarthMike** [comment]
@inamiy Yes makes sense :+1:  Naming is the second hardest problem in programming :smile:

**Comment by inamiy** [comment]
@DarthMike Good to hear you are on this change :wink:

**Comment by inamiy** [comment]
Ready to :shipit:

**Comment by DarthMike** [comment]
I've seen new release. Will try later today or tomorrow :rocket:

**Comment by inamiy** [comment]
Thanks too! Any feedback is welcome :blush:

**Pull request merged**
