### PR TITLE
Swift 1.2

### PR DESCRIPTION
**Pull request by feinstruktur**
Update to Swift 1.2. The swift-1.2 branch is behind a bit so I've started off master as that seems to have worked fine. This is for Xcode-6.3b4. All tests pass.

This assumes you’d want to switch master to swift 1.2, of course.

### CODE REVIEW

**Comment by inamiy** [comment]
Thanks, but can you send me pull request to [swift/1.2](https://github.com/ReactKit/ReactKit/tree/swift/1.2) branch instead?

Ref: https://github.com/ReactKit/ReactKit/issues/15

**Comment by feinstruktur** [comment]
Is it an option to abandon swift/1.2 and create a new branch? The merge is seeing quite a few conflicts that are tricky to disentangle with my limited knowledge of what’s going on. A rebase might have better results but I couldn’t push that on to 1.2.

Let me know!

**Comment by feinstruktur** [comment]
Just to clarify, even a merge from master into swift/1.2 without my above changes causes these conflicts, because those two branches have diverged quite a bit and the swift-1.2 changes touch a lot of areas.

I think it's much more straightforward to abandon the two commits currently sitting on swift/1.2 (they're straightforward changes from the 'Covert to latest swift' pretty much as far as I can tell) and basically redoing that on master (as I essentially have done in this PR).

**Comment by inamiy** [comment]
OK, I reverted my old commits and merged yours to [swift/1.2](https://github.com/ReactKit/ReactKit/tree/swift/1.2) branch manually.
I will then merge this to `master` branch when Swift 1.2 is ready.
So, please keep using `swift/1.2` for a little more time.

Diff: https://github.com/ReactKit/ReactKit/compare/c828575...63d5fae (current master....swift/1.2)

**Comment by inamiy** [comment]
Merged to swift/1.2 branch. Closed.

**Pull request closed without merging**
